[package]
name = "hljs_sample"
version = "0.0.2"
edition = "2021"
publish = false

[dependencies]
pagetop = { version = "0.0", path = "../../pagetop" }
pagetop-hljs = { version = "0.0", path = ".." }
