use pagetop::prelude::*;

use std::collections::HashMap;

/// Supported coding languages.
#[derive(Default, Eq, Hash, PartialEq)]
pub enum HljsLang {
    ActionScript,
    Ada,
    Apache,
    AppleScript,
    Arduino,
    ARMAssembly,
    AsciiDoc,
    AspectJ,
    AutoHotkey,
    AVRAssembly,
    Awk,
    Bash,
    BASIC,
    C,
    Clojure,
    ClojureREPL,
    CMake,
    CoffeeScript,
    Cpp,
    Crystal,
    Csharp,
    CSS,
    D,
    Dart,
    Delphy,
    Diff,
    Django,
    DNSZone,
    Dockerfile,
    DOS,
    Elixir,
    Elm,
    ERB,
    Erlang,
    ErlangREPL,
    Fortran,
    Fsharp,
    Go,
    GraphQL,
    Handlebars,
    Haskell,
    HTML,
    HTTP,
    INI,
    Java,
    JavaScript,
    JSON,
    Julia,
    JuliaREPL,
    Kotlin,
    LaTeX,
    Less,
    Lisp,
    LLVMIR,
    Lua,
    Matlab,
    Makefile,
    Markdown,
    Nginx,
    NodeREPL,
    ObjectiveC,
    Ocaml,
    Perl,
    PHP,
    PHPTemplate,
    #[default]
    Plaintext,
    PostgreSQL,
    PowerShell,
    Prolog,
    Properties,
    Python,
    PythonREPL,
    R,
    Ruby,
    Rust,
    Scala,
    Scheme,
    Scilab,
    SCSS,
    ShellSession,
    Smalltalk,
    SQL,
    Swift,
    Tcl,
    TOML,
    Twig,
    TypeScript,
    VBScript,
    VisualBasicNET,
    WebAssembly,
    X86Asm,
    XML,
    YAML,
}

static LANGS: LazyStatic<HashMap<HljsLang, &'static str>> = LazyStatic::new(|| {
    use HljsLang::*;
    kv![
        // Common languages.
        Bash           => "bash",
        C              => "c",
        Cpp            => "cpp",
        Csharp         => "csharp",
        CSS            => "css",
        Diff           => "diff",
        Go             => "go",
        GraphQL        => "graphql",
        HTML           => "html,xml",
        INI            => "ini",
        Java           => "java",
        JavaScript     => "javascript",
        JSON           => "json",
        Kotlin         => "kotlin",
        Less           => "less",
        Lua            => "lua",
        Makefile       => "makefile",
        Markdown       => "markdown",
        ObjectiveC     => "objectivec",
        Perl           => "perl",
        PHP            => "php",
        PHPTemplate    => "php-template",
        Plaintext      => "plaintext",
        Python         => "python",
        PythonREPL     => "python-repl",
        R              => "r",
        Ruby           => "ruby",
        Rust           => "rust",
        SCSS           => "scss",
        ShellSession   => "shell",
        SQL            => "sql",
        Swift          => "swift",
        TOML           => "toml,ini",
        TypeScript     => "typescript",
        VisualBasicNET => "vbnet",
        WebAssembly    => "wasm",
        XML            => "xml",
        YAML           => "yaml",
        // Other languages.
        ActionScript   => "actionscript",
        Ada            => "ada",
        Apache         => "apache",
        AppleScript    => "applescript",
        Arduino        => "arduino",
        ARMAssembly    => "armasm",
        AsciiDoc       => "asciidoc",
        AspectJ        => "aspectj",
        AutoHotkey     => "autohotkey",
        AVRAssembly    => "avrasm",
        Awk            => "awk",
        BASIC          => "basic",
        Clojure        => "clojure",
        ClojureREPL    => "clojure-repl",
        CMake          => "cmake",
        CoffeeScript   => "coffeescript",
        Crystal        => "crystal",
        D              => "d",
        Dart           => "dart",
        Delphy         => "delphy",
        Django         => "django",
        DNSZone        => "dns",
        Dockerfile     => "dockerfile",
        DOS            => "dos",
        Elixir         => "elixir",
        Elm            => "elm",
        ERB            => "erb",
        Erlang         => "erlang",
        ErlangREPL     => "erlang-repl",
        Fortran        => "fortran",
        Fsharp         => "fsharp",
        Handlebars     => "handlebars",
        Haskell        => "haskell",
        HTTP           => "http",
        Julia          => "julia",
        JuliaREPL      => "julia-repl",
        LaTeX          => "latex",
        Lisp           => "lisp",
        LLVMIR         => "llvm",
        Matlab         => "matlab",
        Nginx          => "nginx",
        NodeREPL       => "node-repl",
        Ocaml          => "ocaml",
        PostgreSQL     => "pgsql",
        PowerShell     => "powershell",
        Prolog         => "prolog",
        Properties     => "properties",
        Scala          => "scala",
        Scheme         => "scheme",
        Scilab         => "scilab",
        Smalltalk      => "smalltalk",
        Tcl            => "tcl",
        Twig           => "twig",
        VBScript       => "vbscript",
        X86Asm         => "x86asm",
    ]
});

impl ToString for HljsLang {
    fn to_string(&self) -> String {
        LANGS.get(self).unwrap().to_string()
    }
}

impl HljsLang {
    pub fn to_url(language: &str) -> String {
        concat_string!("/hljs/js/languages/", language, ".min.js")
    }
}
